name: Terraform Destroy
on:
 workflow_dispatch:

jobs:
 tf-destroy:
   runs-on: ubuntu-latest
   env:
      AWS_ACCESS_KEY_ID: "AKIASM7IGSBIDEHELE6R"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_REGION: "us-east-1"
   steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Terraform                                                                      
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init 
        env:
          AWS_ACCESS_KEY_ID: "AKIASM7IGSBIDEHELE6R"
          AWS_SECRET_ACCESS_KEY: "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"
          AWS_REGION: "us-east-1"
        
      - name: Show Destroy plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: "AKIASM7IGSBIDEHELE6R"
          AWS_SECRET_ACCESS_KEY: "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"
          AWS_REGION: "us-east-1"
        continue-on-error: true

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: "AKIASM7IGSBIDEHELE6R"
          AWS_SECRET_ACCESS_KEY: "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"
          AWS_REGION: "us-east-1"
        
